//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGrupos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public int agencyId { get; set; }
        public string documentType { get; set; }
        public string agencyName { get; set; }
        public string contactType { get; set; }
        public string contactName { get; set; }
        public string cityName { get; set; }
        public string phoneNumber { get; set; }
        public string emailAddress { get; set; }
        public Nullable<bool> terminos { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
